export const bikes = [
  {
    id: 1,
    name: 'Canyon',
    description: 'A road bike to rule them all',
    img: '/images/Canyon.png',
    type: 'roadbike',
    price: 2000,
    built: 2021,
  },
  {
    id: 2,
    name: 'Trek',
    description: 'A road bike for longer rides',
    img: '/images/Trek.png',
    type: 'roadbike',
    price: 3000,
    built: 2020,
  },
  {
    id: 3,
    name: 'Specialized',
    description: 'A road bike for speed maniacs',
    img: '/images/Specialized.png',
    type: 'roadbike',
    price: 1500,
    built: 2023,
  },
  {
    id: 4,
    name: 'Giant',
    description: 'A road bike for bumpy roads',
    img: '/images/Giant.png',
    type: 'roadbike',
    price: 2500,
    built: 2019,
  },
  {
    id: 5,
    name: 'Cannondale',
    description: 'A road bike everyone can afford',
    img: '/images/Cannondale.png',
    type: 'roadbike',
    price: 1000,
    built: 2018,
  },
  {
    id: 6,
    name: 'Cervelo',
    description: 'A road bike when money is no object ',
    img: '/images/Cervelo.png',
    type: 'roadbike',
    price: 4000,
    built: 2022,
  },
];
